#Default configuration file for DarkNessCraft Scoreboard
#Author TimLampen
#################################################################                                                              #                          #                         Prefix Plugin                        #                                                                                                     #											    #
################################################################

prisonprefix:
  Prisoner:
    prefix: '&8┃ &7&oPrisoner &8┃&r'
    weight: 4
    permission: prisonprefix.prisoner
  Owner:
    prefix: '&8┃ &f&oOwner &8┃&r'
    weight: 1
    permission: prisonprefix.owner


#################################################################                                                              #                          #                         ScoreBoard Plugin                    #                                                                                                     #											    #
################################################################
 
CurrentVotes: 150
 
MaxVotes: 150
 

#Everything comes with a default value, so something does need to be put in. MAKE SURE that none of the Pos values are the same (you can use 0).

#Words ending with "t" means title for that thing, for example Plyerst means the title of plyers, try to keep the "t" ending Pos value one bigger than the non-"t" value

#The length of the string most not be more than 16 characters ( %whatever% counts as one) or it will throw errors.

Scoreboard:
#  Plyerst:
#Dealing with the title of plyers
#    Display: "&3&lOnline Peeps"
#What it will look like
#    Pos: 75
#Position of the title (greater the number, the higher up)
#This configuration would make this http://prntscr.com/541ozw
  Title:
    Display: '&6&lMC-DNC'
#Title of the scoreboard

  Plyerst:
#Plyers title
    Display: '&f&lOnline:'
    Pos: 2

  Plyers:
#Plyers value
#%max% = max amount of players
#%players% = players online
    Display: '&7%players%'
    Pos: 1

  Moneyt:
#Money title
    Display: '&f&lCost:'
    Pos: 8

  Money:
#Money value
#%money% = player money
    Display: '&7%money%'
    Pos: 7

  Crnkt:
#Current rank title
    Display: '&f&lRank:'
    Pos: 14

  Crnk:
#Current rank value
#%rank% = player rank
    Display: '&7%rank%'
    Pos: 13

  Nrnkt:
#Next rank title
    Display: '&f&lRankup:'
    Pos: 11

  Nrnk:
#Next rank value
#%number% = % till next rank
    Display: '&7%number%'
    Pos: 10

  Dpt:
#Drop party title
    Display: '&f&lVotes to VP:'
    Pos: 1

  Dp:
#Drop party value
#%vote% = votes needed for drop party
    Display: '&7%vote%'
    Pos: 0

#################################################################                                                              #                          #                         DropParty Plugin                     #                                                                                                     #											    #
################################################################
DropParty:
  AmountOfItems: 1
#The amount of items in the drop party
 
  EndOfDPMsg: "&3End of the drop party!"
#The message that will be broadcasted at the end of the dropparty
 
  StartOfDPMsg: "&3The drop party has started!"
 
  DelayBetweenItems: 5
#The delay between the items being given (seconds)
 
  AmountOfDifferentItems: 10
#The amount of DIFFERENT items you have below (Item1, Item2)

  Commands:
    - "give %player% diamondblock 128"
    - "give %player% emeraldblock 128"
    - "give %player% ironblock 128"
    - "eco give %player% 50000000"
    - "eco give %player% 10000000"
    - "give %player% lavabucket 1"
    - "give %player% waterbucket 1"
    - "give %player% dhelmet 1 name:&bDrop_&cParty_&aHat prot:4 unbreaking:1"
    - "give %player% dchest 1 name:&bDrop_&cParty_&aShirt prot:4 unbreaking:1"
    - "give %player% dleggings 1 name:&bDrop_&cParty_&aLegs prot:4 unbreaking:1"
    - "give %player% dboots 1 name:&bDrop_&cParty_&aShoes prot:4 unbreaking:1"
    - "give %player% dsword 1 name:&bDrop_&cParty_&aSword_&e;) sharp:5 knockback:5 unbreaking:5"
    - "give %player% dpick 1 name:&bDrop_&cParty_&aPick digspeed:25 fortune:10 unbreaking:5"
 
 
#################################################################                                                              #                          #                         NoDrop Plugin                        #                                                                                                     #											    #
################################################################
 
# Add what world(s) to disable the plugin in
settings:
    disabled-worlds:
    - plotworld
 
# Must not skip a level, ability to go up to any Fortune Level
# Format: FORTUNE_LEVEL: MULTIPLER
fortuneLevels:
  lvl15: 1-5
  lvl18: 1-10
  lvl20: 3-6
  lvl25: 1-1
  lvl28: 1-2
  lvl30: 62-100
  lvl40: 13-76
  lvl50: 111-1111
  lvl80: 1-1
  lvl100: 10-20
 
#################################################################                                                              #                          #                         Rankup Plugin                        #                                                                                                     #											    #
################################################################
 
Rankup-Message: '&c[PlayerName] &7has ranked up to &c[Group]&7!'
Must-Be-Player: '&7This command must be ran by a player!'
Not-Enough-Money: |-
  &7You do not have enough money to rankup.
  You need &c&l$[Remainder]&7 more to rankup!
Invaid-Group: |-
  &7You are not in a group that can rank up.
  If you think this is a mistake please contact a server admin.
MineRegions:
  - amine
  - bmine
  - cmine
  - dmine
rankup:
  A:
    cost: 10
    nextrank: B
  B:
    cost: 500000
    nextrank: C
  C:
    cost: 875000
    nextrank: D
  D:
    cost: 6500000
    nextrank: E
  E:
    cost: 10000000
    nextrank: F
  F:
    cost: 30000000
    nextrank: G
  G:
    cost: 600000000
    nextrank: H
  H:
    cost: 1150000000
    nextrank: I
  I:
    cost: 1600000000
    nextrank: J
  J:
    cost: 2750000000
    nextrank: K
  K:
    cost: 4200000000
    nextrank: L
  L:
    cost: 5750000000
    nextrank: M
  M:
    cost: 7500000000
    nextrank: N
  N:
    cost: 10000000000
    nextrank: O
  O:
    cost: 14000000000
    nextrank: P
  P:
    cost: 17570000000
    nextrank: Q
  Q:
    cost: 20500000000
    nextrank: R
  R:
    cost: 35000000000
    nextrank: S
  S:
    cost: 7000000000
    nextrank: T
  T:
    cost: 10300000000
    nextrank: U
  U:
    cost: 17000000000
    nextrank: V
  V:
    cost: 24000000000
    nextrank: W
  W:
    cost: 35000000000
    nextrank: X
  X:
    cost: 50000000000
    nextrank: Y
  Y:
    cost: 65000000000
    nextrank: Z
  Z:
    cost: 80000000000
    nextrank: Warlock
  Warlock:
    cost: 150000000000
    nextrank: Guardian
  Guardian:
    cost: 275000000000
    nextrank: Phantom
  Phantom:
    cost: 350000000000
    nextrank: Emperor
  Emperor:
    cost: 425000000000
    nextrank: Spartan
  Spartan:
    cost: 500000000000
    nextrank: Siren
  Siren:
    cost: 575000000000
    nextrank: Argos
  Argos:
    cost: 3150000000000
    nextrank: Saytre
  Saytre:
    cost: 4300000000000
    nextrank: Kronos
  Kronos:
    cost: 5000000000000
    nextrank: Hades
  Hades:
    cost: 5700000000000

#################################################################                                                              #                          #                        Explosives Plugin                     #                                                                                                     #											    #
################################################################
 
GrenadeCooldown: 5
#The amount of time the player has to wait to throw another grenade
 
RocketCooldown: 10
#same as grenade

EnragedAmount: 500
#Amount of blocks player has to mine to be enraged

KittyChance: 150
#the chance that a cat will appear ex. (if it was 100) then there would be a 1 in 100 chance
#################################################################                                                              #                          #                         Goodie Plugin                        #                                                                                                     #											    #
################################################################
AmountOfDifferentGoodies: 1
#Amount of goodies you have below(Goodie1, Goodie2 etc)

AmountOfGoodieItems: 5
#Amount to give to the player when he clicks the bag

Goodie:
  Commands:
    - "give %player% diamondblock 128"
    - "give %player% emeraldblock 128"
    - "give %player% ironblock 128"
    - "eco give %player% 50000000"
    - "eco give %player% 10000000"
    - "give %player% lavabucket 1"
    - "give %player% waterbucket 1"
    - "give %player% dhelmet 1 name:&bDrop_&cParty_&aHat prot:4 unbreaking:1"
    - "give %player% dchest 1 name:&bDrop_&cParty_&aShirt prot:4 unbreaking:1"
    - "give %player% dleggings 1 name:&bDrop_&cParty_&aLegs prot:4 unbreaking:1"
    - "give %player% dboots 1 name:&bDrop_&cParty_&aShoes prot:4 unbreaking:1"
    - "give %player% dsword 1 name:&bDrop_&cParty_&aSword_&e;) sharp:5 knockback:5 unbreaking:5"
    - "give %player% dpick 1 name:&bDrop_&cParty_&aPick digspeed:25 fortune:10 unbreaking:5"

#################################################################                                                              #                          #                         Scratch Cards                        #                                                                                                     #											    #
################################################################ 
Cards:
#Name of the person who "signed" the card
#All names comes with defaults (dont have to fill these in)
  Name1:
#30% chance
  Name2:
#10% chance
  Name3:
#10% chance
  Name4:
#10% chance
  Name5:
#10% chance
  Name6:
#10% chance
  Name7:
#10% chance
  Name8:
#5% chance
  Name9:
#3% chance (plez no change) - Tim
  Name10:
#2% chance

#################################################################                                                              #                          #                         ColorPick Plugin                     #                                                                                                     #											    #
################################################################ 
ColorPick:
#dont edit unless you know what you are doing
  Suffix:
  Prefix:
#################################################################                                                              #                          #                         Tokens Plugin                        #                                                                                                     #											    #
################################################################ 
tokens:
 
#################################################################                                                              #                          #                         Messages                             #                                                                                                     #											    #
################################################################
 
#All messages come with defaults, so you dont need to input a value
 
Messages:
  SyntaxError:
#Thrown when the player does not to a correct command.
 
  PermissionError:
#Thrown when the player does not have correct permission.
 
  NullNumber:
#Thrown when player inputs a character where there is suppose to be a number. Can input %number% in the message to act as the character that the player inputted.
 
  NullPlayer:
#Thrown when the user the player requested is not online. Can input %name% in the message to act as the name that the player inputted.
 
 
  DPRestart:
#Message sent to player when the drop party counter is reset
 
  DPStart:
#Message sent to player when the drop party starts by command
 
  DPSet:
#Message sent to player when he sets the drop party counter. Can use %number% as the number that the player used
 
  MultiGetSet:
#Message sent to the TARGET player who GETS their multipler set to a number. Can use %player% as the name who set the multipler, and %number% as the multipler number that it was set to.
 
  MultiSet:
#Message sent to the ORIGINAL player who SETS another persons to a number. Can use %player% as the TARGET name, and %number% as the multipler number that it was set to.
 
  GrenadeGet:
#Message sent to the TARGET player who GETS a number of grenades. Can use %player% as the name who gave them grenades, and %number% as the amount of grenades the player was given.
 
  GrenadeGive:
#Message sent to the ORIGNAL player who GIVES a number of grenades. Can use %player% as the name who grenades were given to, and %number% as the amount of grenades the player was given.
 
  RocketGet:
#Message sent to the TARGET player who GETS a number of rockets. Can use %player% as the name who gave them rockets, and %number% as the amount of rockets the player was given.
 
  RocketGive:
#Message sent to the ORIGNAL player who GIVES a number of rockets. Can use %player% as the name who rockets were given to, and %number% as the amount of rockets the player was given.

  InvFull:
#Message sent to the palyer when their entire inventory is full
